name: Build Package
on:
  push:
    branches-ignore:
      - "main"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: | 
          ./build_scripts.sh pip
          ./build_scripts.sh test
  build:
    needs: [test]
    name: Build Wheel
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - uses: actions/checkout@v2
      - name: Exceute Wheel Build 
        if: "!cancelled() && !failure()"
        run: |
          ./build_scripts.sh pip
          ./build_scripts.sh build
